version: "3.2"
volumes:
  datafiles:
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on: 
            - sql-server-db
        ports:
            - "8080:80"
        restart: always
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
    sql-server-db:
        container_name: "sql-server-db-local"
        image: "mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04"
        ports:
            - "1433:1433"
        volumes:
            - D:\Programming\КУРСОВІ\SportsHubSystem\mssql\data:/var/opt/mssql/data
        environment:
            SA_PASSWORD: "I8well4sure"
            ACCEPT_EULA: "Y"