# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./SportsHub
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore SportsHub.sln
    - name: Build
      run: dotnet build SportsHub.sln --no-restore
    - name: Test
      run: dotnet test SportsHub.sln --no-build --verbosity normal
